### ISSUE TITLE
type definition

### ISSUE THREAD

**Issue by atoy40** [trojanowski/react-apollo-hooks#10]
Hi
react-apollo redefine FetchResult and ExecutionResult type to get the correct type for the data object available in the mutation promise :
https://github.com/apollographql/react-apollo/blob/49ceaae683599e058009606eed9f933edab5886e/src/Mutation.tsx#L38
https://github.com/apollographql/react-apollo/blob/49ceaae683599e058009606eed9f933edab5886e/src/Mutation.tsx#L25

Is it possible to do the same in your hooks version ?
Anthony.

**Comment by trojanowski** [comment]
Hi @atoy40 ,

Good catch, we can create a similar version of `FetchResult` in our hooks. I wonder why where is no `ExecutionResult<C>` in [apollo-link types](https://github.com/apollographql/apollo-link/blob/aa54dd03cecc3dc2794cd424da950c6970a4381d/packages/apollo-link/src/types.ts#L26).

**Comment by trojanowski** [comment]
It's fixed in 0.1.2. Now the following snippet should work:

```typescript
const TEST_MUTATION = gql`...`;

type SampleMutationResult = {
  fieldA: string;
  fieldB: number;
};

type SampleMutationVariables = {
  varA: string;
};

const Test: React.SFC<{}> = () => {
  const mutate = useApolloMutation<
    SampleMutationResult,
    SampleMutationVariables
  >(TEST_MUTATION);
  async function handleClick() {
    const result = await mutate({ variables: { varA: 'A' } });
    const { data } = result;
    if (data != null) {
      // data has `SampleMutationResult` type here
      console.log(data.fieldA);
    }
  }

  return <button onClick={handleClick}>Test</button>
};
```

**Comment by atoy40** [comment]
Hi,
I've checked your code, but you don't refdefine ExecutionResult. This is the real "gulty" because it is not parametrized, data has a fixed type ObjMap<mixed> : https://github.com/graphql/graphql-js/blob/f529809f5408fb9a343e669ea4d4851add3df004/src/execution/execute.js#L114
I think this is why apollo-link FetchResult is not parametrized too.

Thanks
Anthony.

**Comment by trojanowski** [comment]
There's flowtype source code in the link from your comment. TypeScript definitions have `ExecutionResult` parametrized: <https://github.com/DefinitelyTyped/DefinitelyTyped/blob/26d2add0dbab432d664ecaff63206b06e5b1aadd/types/graphql/execution/execute.d.ts#L49>. The snipped from my previous comment works for me with 0.1.2 (`data` has a correct type).
