### ISSUE TITLE
react-apollo-hooks should follow spec of their respected Render Prop APIs

### ISSUE THREAD

**Issue by lifeiscontent** [trojanowski/react-apollo-hooks#101]
see example here on how to do that:

https://github.com/kentcdodds/react-github-profile/blob/bad3daefe83f14141d64c13712ffe1de41ccaa2a/src/screens/user/components/query.js#L45-L82

specifically line 82

also to make refactoring easier, you should provide Query, Mutation, etc as Components, so people moving to this API will have an easy transition.

**Comment by trojanowski** [comment]
@lifeiscontent it's possible to use both react-apollo and react-apollo-hooks together, so you should be able to migrate each component separately.
