### ISSUE TITLE
Can this library be used with Apollo Client 2.5? 

### ISSUE THREAD

**Issue by richardjli** [trojanowski/react-apollo-hooks#104]
My apologies, I tried to search for this answer but could not find it. Does anything need to be done for react-apollo-hooks to work with Apollo Client 2.5? 

Do I need both react-apollo and react-apollo-hooks in this scenario?

**Comment by lukasluecke** [comment]
I am using it with 2.5 successfully (and with the new local state management), I have both react-apollo and react-apollo-hooks installed.

**Comment by trojanowski** [comment]
Yes, it can. Please fill an issue if you have any problems with it.
