### ISSUE TITLE
Adding hooks for apollo-link-state

### ISSUE THREAD

**Issue by evanheckert** [trojanowski/react-apollo-hooks#11]
Curious if you'd be interested in adding hooks for Apollo Link State? I've struggled a bit with finding a simple/repeatable way to use it, and hooks seem like they may be exactly what the doctor ordered.

**Comment by trojanowski** [comment]
Hi @evanheckert 

What additional hooks do you mean? I thought that the idea of apollo-link-state is to use the same interface for both local and remote queries. It's possible to use it right now, e.g. a port of Pupstagram sample app is using it: <https://codesandbox.io/s/8819w85jn9>

**Comment by evanheckert** [comment]
Thanks @trojanowski , I'm still wrapping my mind around what hooks can be used for. I went through that example page by page just now, and I see what you mean as far as how react-apollo-hooks is used for local queries. Thanks for making this, and for your quick reply!
