### ISSUE TITLE
How to make the query optimistic?

### ISSUE THREAD

**Issue by janhesters** [trojanowski/react-apollo-hooks#110]
I can't figure out, how to make the queries optimistic. I'm using the API like this:

```js
const deleteContact = useMutation(gql(mutations.deleteContact));

handleClick = async id => {
  const res = await deleteContact({ variables: { input: { id } } });
  console.log('Delete Contact', res);
}
```

And res has `Symbol(isOptimistic): false`. How can I make that `true`?

**Comment by lukasluecke** [comment]
You can pass the additional options `optimisticResponse` and `update` to your call of `deleteContact`. Check the Apollo docs for details, there‘s no difference using hooks.

**Comment by janhesters** [comment]
@lukasluecke Hmm that is what I'm doing, but I still get `Symbol(isOptimistic): false`. I guess the error is somewhere else... I'm gonna close this and deep dive more 😭

**Comment by lukasluecke** [comment]
I am not sure about `isOptimistic`, but I have successfully used optimistic mutations with hooks. Does your update function get called?

**Comment by janhesters** [comment]
@lukasluecke I don't know for sure. I'm completly new to GraphQL (literally started last week). I'm trying to use `react-apollo-hooks` with AWS AppSync and use a lot of their helper functions like this:

```js
const deleteContact = useMutation(
    graphqlMutation(
      gql(mutations.deleteContact),
      gql(queries.listContacts),
      'Contact'
    )
  );
```

But I'm still learning how these helpers work. They are supposed to be used like this in regular React Apollo:

```js
export default compose(
  graphqlMutation(gql(mutations.createContact), ListContacts, 'Contact'),
  graphql(ListContacts, {
    options: { fetchPolicy: 'cache-and-network' },
    props: ({ data: { listContacts, error, loading } }) => ({
      data: listContacts ? listContacts.items : [],
      error,
      loading
    })
  })
)(ContactList);
```

**Comment by lukasluecke** [comment]
I don't have any experience using AWS AppSync or their helpers, sorry. I'd suggest you try it without them first, and see if that works.

```js
const deleteContact = useMutation(gql(mutations.deleteContact));

handleClick = async id => {
  const res = await deleteContact({
    variables: { input: { id } },
    optimisticResponse: {
      __typename: "Mutation",
      deleteContact: {
        id
      }
    }
    update: (cache, response) => { console.log(response); /* cache.writeData(...) */ }
  });
  console.log('Delete Contact', res);
}
```

**Comment by janhesters** [comment]
I'll try it. Thank you for your help! BTW, [here are the relevant AppSync Docs](https://aws-amplify.github.io/docs/js/api#offline-mutations). I will use their code for the `update` key.

**Comment by janhesters** [comment]
@lukasluecke Oh yeah, one more follow up question. Do you think I could use the `buildMutation` helper (from the link of my last comment) if I pass it client from `useApolloClient`?

**Comment by janhesters** [comment]
@lukasluecke It works! It's super verbose, but I guess that is the best that it can be at the moment. Thank you for your help 🚀

**Comment by lukasluecke** [comment]
Great! Yeah, the manual cache update stuff always feels a bit cumbersome, even with "plain" Apollo.

> Do you think I could use the `buildMutation` helper (from the link of my last comment) if I pass it client from `useApolloClient`?
That might work, but then you would bypass the mutation hook altogether ;)
