### ISSUE TITLE
Skip option in `useQuery` doesn't actually skip the query

### ISSUE THREAD

**Issue by galencorey** [trojanowski/react-apollo-hooks#113]
I ran into an issue where passing `{ skip: true }` as an option into `useQuery` does not actually skip the query.  I isolated it here in a fork of the codesandbox example: https://codesandbox.io/s/kx0z271l15

In `src/views/Feed.js` line 26, I added `{ skip: true }` to the second argument of the `useQuery` hook.  I also am logging the result to the console for extra verification. These were the only changes I made to the example provided in this repo. All of the info still renders, regardless of whether that skip option is there or not. And if you check the console, you will see that it is still fetching all the data. To me, this is not expected behavior.

**Comment by nino-moreton** [comment]
Still not yet released as per https://github.com/trojanowski/react-apollo-hooks/issues/43

**Comment by trojanowski** [comment]
@galencorey you're using an old version (0.2.0) in your example. `skip` was introduced in 0.3.0 and should work with the latest version.

**Comment by shuzootani** [comment]
@trojanowski so it returns undefined for `data`?
I'm a bit confused about what this docs means.
https://www.apollographql.com/docs/react/api/react-hooks/#options
> If skip is true, the query will be skipped entirely.

are there any effects other than returning undefined for data prop?
