### ISSUE TITLE
[useQuery] Doesn't return data if there is an error

### ISSUE THREAD

**Issue by Dastari** [trojanowski/react-apollo-hooks#119]
This may sound normal.. if there's an error we don't need the data right?

In my case the returning JSON has errors and a data response. I'm using errors for:

**1)** Alerting that the query they have attempted includes a field they do not have authorization to use (using the Authorization decorator on the server)
**2)** That one of the particular values isn't correctly formed to match the schema

Example Result:

```JSON
{
	"errors": [{
			"message": "Value is not a valid postal code: 1234",
			"locations": [{
					"line": 7,
					"column": 5
				}
			],
			"path": [
				"results",
				4,
				"postcode"
			]
		}, {
			"message": "You do not meet the requirements to query this field.",
			"locations": [{
					"line": 7,
					"column": 5
				}
			],
			"path": [
				"results",
				13,
				"ipaddress"
			]
		}
	],
	"data": {
		"results": [{
				"id": "DDFC423E-F36B-1410-8841-004B4332510D",
				"name": "The Name of Something",
				"address": "Some Address",
				"town": "It's Town",
				"isPublished": false,
			},
			{ .... }
		]
	}
}
```

So is there a way to get the data results even if there is an error?

**Comment by jurajkrivda** [comment]
I think you have to set up error policy on your query.

**Comment by Dastari** [comment]
Awesome thanks :)
