### ISSUE TITLE
TypeError: Object(...) is not a function  when  const client = useApolloClient();

### ISSUE THREAD

**Issue by killjoy2013** [trojanowski/react-apollo-hooks#12]
Hi,

Getting 
TypeError: Object(...) is not a function  
when  const client = useApolloClient();  inside the component.

Thanks

**Comment by trojanowski** [comment]
Hi @killjoy2013 

Could you please provide more details or ideally create a reproducible Demo on <https://codesandbox.io> or github? `useApolloClient` works in the example app: <https://codesandbox.io/s/8819w85jn9> (please look at _src/views/Feed.js_).

**Comment by voxtex** [comment]
Make sure you have react@next AND react-dom@next installed. Had a similar error using React Hooks API with create-react-app. Both need to be 16.7+.

**Comment by atoy40** [comment]
@killjoy2013 I had the same problem when @next was 16.7.0-alpha1 ... then some hours later, the alpha2 came and fixed it. so check you react/react-dom version.

**Comment by trojanowski** [comment]
@killjoy2013 I'm going to close it. If you still have this problem and ensured you use the latest alphas for both react and react-dom, please add a comment.

**Comment by timburgess** [comment]
FYI, both `react@canary (0.0.0-c5b7d26c7)` and `react@unstable (0.0.0-0c756fb-f7f79fd)` produce this error whereas alpha2 works.

**Comment by trojanowski** [comment]
@timburgess Have you ensured you use exactly the same version of both react and react-dom?

**Comment by timburgess** [comment]
@trojanowski Yes. Upgraded a working project with `npm install --save --save-exact react@canary react-dom@canary` and got:

![screenshot from 2018-12-08 20-07-15](https://user-images.githubusercontent.com/28915/49684846-38329180-fb25-11e8-8c3a-0a8060eac897.png)

**Comment by adrenalien** [comment]
Oh, my bad, sorry.

It works! Thanks for your quick answer and your great job

**Comment by caprica-Six** [comment]
works here as well, noticed also `react-scripts` should be 2.1.1, _not_ 2.1.2
`"react": "^16.7.0-alpha.2"`,
`"react-dom": "^16.7.0-alpha.2",`
`"react-scripts": "2.1.1"`

**Comment by pitops** [comment]
I tried to use the following in package.json but do not work.

```bash
    "react": "16.7.0-alpha.2",
    "react-dom": "16.7.0-alpha.2",
```
What worked is the following

```bash
    "react": "next",
    "react-dom": "next",
```

**Comment by fsultani-aspiration** [comment]
Same problem.  package.json had
```
"react": "^16.7.0-alpha.2",
"react-dom": "^16.7.0-alpha.2",
```
and it wasn't working.  Change it to 
```
"react": "next",
"react-dom": "next",
```
and it worked.

**Comment by pitops** [comment]
@fsultani-aspiration  yes its best to use the version without the `^`.

Latest hooks version

```bash
"react": "16.8.0-alpha.0",
"react-dom": "16.8.0-alpha.0"
```
