### ISSUE TITLE
Replace custom ApolloContext with official one

### ISSUE THREAD

**Issue by FezVrasta** [trojanowski/react-apollo-hooks#131]
Starting from react-apollo@2.5.3 we have access to the ApolloContext (https://unpkg.com/react-apollo@2.5.3/ApolloContext.js).

This would enable this library to get rid of the custom `ApolloProvider` and `ApolloContext` and just rely on `react-apollo`

**Comment by trojanowski** [comment]
It's not exposed in the cjs and esm builds: <https://unpkg.com/react-apollo@2.5.4/react-apollo.cjs.js>.

**Comment by FezVrasta** [comment]
Oh 😓

**Comment by FezVrasta** [comment]
The next version should expose it.

https://github.com/apollographql/react-apollo/pull/2961

**Comment by FezVrasta** [comment]
`react-apollo@2.5.5` exposes its context!

**Comment by FredyC** [comment]
Well, I think we can just reexport ApolloContext instead of a custom one. And the provider from this package should yield a deprecation warning and use `ApolloContext.Provider` internally. That won't break anything AFAIK.

**Comment by FezVrasta** [comment]
So:

1. Make `react-apollo-hooks`' `ApolloProvider` point to `react-apollo` context
2. Add `react-apollo@^2.5.5` as peer dependency
3. profit?

**Comment by FredyC** [comment]
Actually, I've managed to migrate the app to hooks so I've dropped the `react-apollo` from dependencies altogether. Hm, that's bummer. I don't want to add it again just because of the context :/

I guess it would need to safely detect if `react-apollo` is available and fall back to custom context if not.

**Comment by FezVrasta** [comment]
Doing `import { ApolloContext } from 'react-apollo'` will throw an error in webpack/bundler-of-choice if the dependency is not available. How can you import only if the package is available?

**Comment by FredyC** [comment]
Yea, that's the tricky part. Sadly I am not aware of any safe way of doing that. I do remember seeing a trick like this but never tried if it actually works.

```jx
const r = require
try {
  r('react-apollo')
} catch (e) {
  // not available
}
```

Perhaps it's not such a good idea doing this after all. I mean this package eventually will be merged to the official one. We just need to be patient.

**Comment by FezVrasta** [comment]
Alternatively we could make `react-apollo` a dependency, this would make the whole thing transparent to the consumer.

**Comment by FredyC** [comment]
I suppose that would work, but it feels like excessive dependency just to be there just for such a little piece of information. I don't know, I feel it's not such a big deal in the end to have two providers. Initially, I made myself this piece of code to abstract such a detail away.

```tsx
import { ApolloProvider as ApolloProviderHooked, useApolloClient } from '@speedlo/react-apollo-hooks'
import React from 'react'
import { ApolloProvider as ApolloProviderOrig, ApolloProviderProps } from 'react-apollo'

export function ApolloProvider<TCache>({
  client,
  children,
}: ApolloProviderProps<TCache>) {
  return (
    <ApolloProviderOrig<TCache> client={client}>
      <ApolloProviderHooked<TCache> client={client}>
        {children}
      </ApolloProviderHooked>
    </ApolloProviderOrig>
  )
}

export { useApolloClient }
```

**Comment by FezVrasta** [comment]
It's not a big deal, but people get easily scared by it. In my team I received concerns from several team members because of that provider, they think this library tries to replace Apollo completely.

I know it's not this library's fault, but it's something that could be easily avoided if the README told the users this library can be used in their current `react-apollo` applications by just importing and using the hooks exposed by it.

**Comment by FredyC** [comment]
Honestly, if someone is not using `react-apollo-hooks` yet, they are most likely waiting for it to stabilize and become part of the `react-apollo`. People who already embraced hooks have two providers anyway.

Let's some other people chime in on this or you can prepare some preliminary PR and we can go from there.

**Comment by trojanowski** [comment]
I agree with @FredyC.  It's often possible to replace all HOCs / render props with hooks (or just start with hooks and don't use alternative APIs at all, e.g. in new projects). And after that, it's easier to install only one library, instead of two. And if you want to use react-apollo and react-apollo-hooks together, the integration is quite simple. @FezVrasta if you don't agree with that maybe a better idea will be to improve the documentation?

**Comment by FezVrasta** [comment]
I think the documentation is fine, it's just the developer experience that lacks

**Comment by dantman** [comment]
I use both react-apollo and react-apollo-hooks, I probably won't ever just use react-apollo-hooks on it's own. So a dependency on react-apollo to reduce the provider duplication wouldn't hurt me.

For context, so far I am using `<Query>` for most of my querying and `useMutation` for most of my mutations. `useQuery` cannot be done conditionally (e.g. you have a query that requires `account.id` but need a conditional guard against `account === undefined`). And `<Query>` can also be done deeply without re-rendering the whole containing component for just a partial tree change.

**Comment by FredyC** [comment]
@dantman For conditional querying, I made my own `Query` based on `useQuery`. Sometimes I opt for using `skip` in simple cases and when I need to access data in the body of a function. Render prop is just awkward with hooks around :)

**Comment by FezVrasta** [comment]
The material forms are in their own section 
https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/forms/
