### ISSUE TITLE
Calling setState after on useQuery data triggers infinite loop

### ISSUE THREAD

**Issue by mikefisher84** [trojanowski/react-apollo-hooks#133]
I've been using apollo-hooks in my app and so far I love it except I can't get pass this issue. 

I'm using useQuery to return an array of users to display in a list. However I want to store those users in local state using `useState` so that when I click a delete button next to the user it deletes them from the list. However whenever I call `useState on data from `apollo-hooks` I get this error. 

` Invariant Violation: Too many re-renders. React limits the number of renders to prevent an infinite loop.`

I'm not sure what I'm doing wrong, any insight would be helpful. Here's some of my code. 

```js
const [user, setUser] = useState('');
  const [list, setList] = useState([]);

  useEffect(() => {
    if (storage.hasUser()) {
      const user = storage.getUser();
      setUser(user);
    } else {
      history.push('/login');
    }
  }, []);

  const { accessToken, organizationId } = user;

  const { data, error, loading } = useQuery(GROUPS_PAGE_QUERY, {
    variables: {
      accessToken: accessToken,
      organizationId: organizationId
    }
  });

  if (data) {
    setList(data); // this seems to be where the error is happening. 
  }

return (
    <div>
      <GroupList groups={data.userGroups} deleteGroup={deleteGroup} />
    </div>
  );
```

**Comment by JaosnHsieh** [comment]
I encountered the same problem, this is my workaround. use `useMemo`.

In your example:

```javascript
import React, { useState, useMemo, useEffect } from 'react';

...

   const { data, error, loading } = useQuery(GROUPS_PAGE_QUERY, {
    variables: {
      accessToken: accessToken,
      organizationId: organizationId
    }
  });

  useMemo(()=>{
    setList(data); 
  },[data])

...

```

**Comment by ThomasK33** [comment]
This is a React Hooks misunderstanding and not an issue with this library.

Each `set[...]` call (more detailed the second element in the array) from a `useState` causes a re-render of the component containing the hook.

Let's apply this to your code:

```javascript
const [user, setUser] = useState('');
const [list, setList] = useState([]);

  useEffect(() => {
    if (storage.hasUser()) {
      const user = storage.getUser();
      setUser(user);
    } else {
      history.push('/login');
    }
  }, []);
```

This effect call is going to be executed once.
If the storage has a user it will set the user and cause the component to re-render with the set user. 
In this new re-render, this effect wont be called again as the deps array did not change any values.

```javascript
  const { accessToken, organizationId } = user;

  const { data, error, loading } = useQuery(GROUPS_PAGE_QUERY, {
    variables: {
      accessToken: accessToken,
      organizationId: organizationId
    }
  });
```

A query is executed with the `useQuery` function.
`useQuery` is a hook and will return an object containing a response.

Assuming the data is not going to change on the server and / or the local cache, this response will always result the same data. (considering same query && params)

```javascript
  if (data) {
    setList(data); // this seems to be where the error is happening. 
  }

 [...]
```

As you correctly pointed out, an infinite re-render loop starts in this line.

If one finished loading (loading == false) and there have been no errors (error == null), one's data might not be null and might be set.

Assuming data != null, this condition will be true on every subsequent re-render as the server / cached response will not change.

Hence one ends up with an infinite loop, as `setList` calls will trigger a re-render that check for `data != null` and trigger a `setList` calls that re-renders (and so on...).

---

To fix this issue, either directly use the `data` variable from the `useQuery` hook or consider using a [React Ref](https://reactjs.org/docs/hooks-reference.html#useref).

Also if you do not require the `data` from the `useQuery` in this component, don't query it.
Query it with the component that is going to use it.

---

On a side note: the workaround presented above is more of a hack than dealing with the elephant in the room.
So while it's true, that by using memoization one can manage to get out of the re-render cycle, it is a "fix" to a misconception in the use of hooks.

**Comment by mikefisher84** [comment]
Thanks @ThomasK33 and I did indeed suspect I was using hooks improperly here which was causing the re-rendering. 

The real thing I'm trying to achieve here is simply having the ability to query and mutate a list as easy as possible. 

Imagine a todo app where each todo item as a delete button on it and the list of todos is very long.

My approach was to Query for the todos and store them in an array with setState. Then when a delete button is clicked we fire off a mutation but also update setState with the missing todo item. That way we don't have to wait for the new Query every-time (right now the list is long and it takes some time for the query to fully render) 

Perhaps there's a better approach to this?

**Comment by ThomasK33** [comment]
In that case, you'd rather want to modify your apollo cache by hand.

Take a look at the [local state management docs](https://www.apollographql.com/docs/react/essentials/local-state) from apollo.

---

Aside from that: Depending if you have access and / or can modify the GraphQL backend, you might consider adding a status field to each list element.
You would then query each list element with its ID (even if you don't use it anywhere) and when firing off the mutation, you'd return the element with its ID and the "new" status.

Doing so, the apollo cache would automatically update the item(s) in the cache based on the ID and the component using the initial list query would re-render with the up to date cache. (This of course assumes that you'd then filter by status in the frontend.)

**Comment by mehmetnyarar** [comment]
@ThomasK33 you mentioned using `useRef`. Could you give an example if you don't mind?

**Comment by omarvelous** [comment]
Arrived here, thanks for the explanation @ThomasK33. We should consider removing the snippet of code that encourages this found here: https://www.apollographql.com/docs/react/data/queries/#executing-queries-manually

```
if (data && data.dog) {
  setDog(data.dog);
}
```

**Comment by fsjsd** [comment]
Great answer from @ThomasK33.

Another solution I've run with rather than wrapping lots of useCallback/useMemo around things is to abstract the useQuery hook into a custom hook and wrap just that in a memo that prevents re-run unless there's changes to props/state (in this case your setList call), and prevents it running unless there's valid state for the variables/arguments.

**Comment by dandv** [comment]
> The real thing I'm trying to achieve here is simply having the ability to query and mutate a list as easy as possible.

If you're open to considering a better suited tool for the job, Meteor makes it transparent and painless to have the data in sync between the server and the client.

**Comment by alihesari** [comment]
https://stackoverflow.com/questions/57577102/store-data-from-usequery-with-usestate

**Comment by gustawdaniel-acaisoft** [comment]
in my case this was wrong code

```
  const sub = useSubscription(
    MESSAGE_CREATED,
    {variables: {where: {chatId: Number(id)}}}
  );

  if(sub.data && sub.data.messageCreated) {
    const newMessage = gqlMessageToIMessage(sub.data.messageCreated);
    setAllMessages(GiftedChat.append(allMessages, [newMessage]));
  }
```

And tehre is fixed

```
  const sub = useSubscription(
    MESSAGE_CREATED,
    {variables: {where: {chatId: Number(id)}}}
  );

  if(sub.data && sub.data.messageCreated) {
    const newMessage = gqlMessageToIMessage(sub.data.messageCreated);
    if(!allMessages.find(m => m._id === newMessage._id)) {
      setAllMessages(GiftedChat.append(allMessages, [newMessage]));
    }
  }
```

**Comment by jairmedeiros** [comment]
Reviving this thread, sorry about this guys. But there is a good way to really use the `useState` with `useQuery` in same component? I have the data coming from `useQuery` and through the `useState` manipulate it, like filtering.

I tried to update the state within `useEffect`, but as all the component re-rendered, the loop keeps 😞 .

**Comment by fbartho** [comment]
@jairmedeiros you can use `useMemo` To filter results from the `useQuery` call, if that helps?

**Comment by diegosound** [comment]
@jairmedeiros https://reacter.space/questions/react-useeffect-causing-repetitive-fetching-from-api

**Comment by fbartho** [comment]
@diegosound stop spamming. This is unsolicited, unhelpful content. I’ve noticed a bunch of similar style messages on different open source projects today.
