### ISSUE TITLE
useQuery inside getInitialProps of next.js

### ISSUE THREAD

**Issue by BjoernRave** [trojanowski/react-apollo-hooks#136]
Hey, I was thinking if there is a way to make it possible to use `useQuery` inside the getInitialProps function of next.js to do the initial data fetching?

**Comment by ThomasK33** [comment]
`useQuery` is a React Hook and Hooks can only be used in a function component (as pointed out in the [React docs](https://reactjs.org/docs/hooks-overview.html)).

If you want to have a graphql query run in the `getInitialProps` method / function provided by Next.js consider using the apollo client directly.

Example (leaving out imports):

```javascript

const Component = () => {
  return <div>Component</div>;
};

Component.getInitialProps = async() => {
  const { loading, errors, data } = await apollo.query({query: "{ version }"}); // assuming your apollo client is called "apollo" and you replace "{ version }" with your own query

  // Your business logic in getInitialProps
};

export default Component;

```

**Comment by BjoernRave** [comment]
@ThomasK33 thanks for the reply. Yea I know this about hooks, was just wondering if there was any workaround.

From where are you importing `apollo` ? 
I checked the imports from `apollo-client`, but nothing really fits

**Comment by ThomasK33** [comment]
The later one. 

In my example I am using an already instantiated ApolloClient. 

Head over to the docs of [„next-with-apollo“](https://github.com/lfades/next-with-apollo/blob/master/README.md) to find out how to access the apollo client in „getInitialProps“.

**Comment by BjoernRave** [comment]
@ThomasK33 thanks for the help, works for me now :)
