### ISSUE TITLE
renderToNodeStream and window.__APOLLO_STATE__ in footer

### ISSUE THREAD

**Issue by secretlifeof** [trojanowski/react-apollo-hooks#139]
Using renderToNodeStream apollo adds another graphQL-query client-side, when window.__APOLLO_STATE__ is located in the footer/at the bottom of the HTML-document.

I can see a flickering resulting from a re-rendering of the react-component (useQuery loading is shown). If I turn off javascript in the browser everything renders as expected.

This behaviour is not observed when window.__APOLLO_STATE__ is added to HTML-head.

Being a beginner I imagine this behaviour coming from: The javascript/apollo-app loads quicker and before the footer has been streamed, leading to window.__APOLLO_STATE__ being interpret as being null.

I have created this small repository to recreate the problem from my bigger app:
https://github.com/secretlifeof/firstParcel.

What I have tried:
- Using Parcel and Razzle without change
- SSRForceDelay to ApolloClient without change

Do you know any solution to this?

react-apollo-hooks: 0.4.5
react-dom: 
node: 11.9
apollo-cache-inmemory: 1.5.1
apollo-client: ^2.5.1
apollo-link-http: ^1.5.14
apollo-utilities: ^1.2.1

**Comment by trojanowski** [comment]
The only supported way of doing SSR with react-apollo-hooks is `getMarkupFromTree`: <https://github.com/trojanowski/react-apollo-hooks#server-side-rendering>. It only support `renderToString` and `renderToStaticMarkup`. It doesn't support stream rendering, and I don't think it will be. Long term solution to this problem will be [a new React server renderer that supports Suspense](https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#suspense-for-server-rendering).
