### ISSUE TITLE
Miss a lot of things? or it's me

### ISSUE THREAD

**Issue by efichot** [trojanowski/react-apollo-hooks#14]
Great work, but how I can access subscribeToMore on query hook and update the cache after a mutation with this hooks?

**Comment by trojanowski** [comment]
Hi @efichot 

> how I can access subscribeToMore on query hook

Right now it's not implemented. I'm going to add a separate hook for subscriptions.

> and update the cache after a mutation with this hooks

By using the `update` option of the `useMutation` hook:

```
const toggleLike = useMutation(TOGGLE_LIKED_PHOTO, {
    variables: { id: imageId },
    update: () => { /* your update logic here */ }
  });
```

**Comment by efichot** [comment]
Ok perfect maybe you need to add this on the README, not sure.
Keep the good work

**Comment by kamalbennani** [comment]
@trojanowski Did you get the time to work on subscribeToMore?
