### ISSUE TITLE
How to call client.writeData with react-apollo-hooks? 

### ISSUE THREAD

**Issue by mikefisher84** [trojanowski/react-apollo-hooks#142]
I'm trying to write login and logout functionality using this library. The `react-apollo` docs have a clear example of how to achieve this using the render props approach but I can't figure out how to achieve this with this library. Specifically I want write data to the client to say that I'm logged in. As seen here. 

```js
export default function Login() {
  return (
    <ApolloConsumer>
      {client => (
        <Mutation
          mutation={LOGIN_USER}
          onCompleted={({ login }) => {
            localStorage.setItem('token', login);
            client.writeData({ data: { isLoggedIn: true } });
          }}
        >
          {(login, { loading, error }) => {
            // this loading state will probably never show, but it's helpful to
            // have for testing
            if (loading) return <Loading />;
            if (error) return <p>An error occurred</p>;

            return <LoginForm login={login} />;
          }}
        </Mutation>
      )}
    </ApolloConsumer>
  );
}
```

**Comment by ostrebler** [comment]
Have you tried using the[ `useApolloClient`](https://github.com/trojanowski/react-apollo-hooks#useapolloclient) hook ?

**Comment by mikefisher84** [comment]
> Have you tried using the[ `useApolloClient`](https://github.com/trojanowski/react-apollo-hooks#useapolloclient) hook ?

Doh! How did I miss this? I've read these docs so many times

**Comment by oceandrama** [comment]
I'm trying to do exactly the same as @mikefisher84 
In my `SignIn` component I update my cache after successful login
```js
  const signIn = useSignInMutation({
    update: (proxy) => {
      proxy.writeData({ data: { authStatus: 'yes' } });
    },
  });
```

In my `AuthWindow` component I want to check `authStatus` and show children instead of `SignIn` component
```js
const getAuthStatus = gql`
  query {
    authStatus
  }
`;

const client = useApolloClient();

const { authStatus } = client.readQuery({
    query: getAuthStatus,
  });

return (
    <Fragment>
      {authStatus === 'yes' && children}
      {authStatus === 'no' && <SignIn />}
    </Fragment>
  );
```
But after `proxy.writeData` my `AuthWindow` component not rerender with new value of `authStatus`
