### ISSUE TITLE
Query option `pollInterval` seems to be ignored

### ISSUE THREAD

**Issue by mrtnpro** [trojanowski/react-apollo-hooks#143]
It seems to me that `useQuery` doesn't pass `pollInterval` down to the query.

Running this code:
```es6
const { data, startPolling, stopPolling } = useQuery(QUERY, { pollInterval: 1000 })

startPolling()
```

Results in the following error:
```
Uncaught Invariant Violation: Attempted to start a polling query without a polling interval
```

Am I missing something?

**Comment by numso** [comment]
I believe when you set a pollInterval in your options, apollo immediately starts polling for you.

If you want to pause/resume later in your app, you would call `stopPolling` followed later by `startPolling(1000)`. (Note, that the interval is a required argument in startPolling).

If you don't want polling to start automatically, you'd omit it from your query options and manually call `startPolling(1000)` later.

**Comment by tuucan** [comment]
I had another problem with pollInterval. When I give it X seconds interval, it seems to be polling every 2X seconds. Is there anyone experiencing this or am I missing something?

```js
const { data } = useQuery(QUERY, {  
    variables: { someVariable },  
    pollInterval: 5000,  
})
```

It polls every 10 seconds.

**Comment by mrtnpro** [comment]
> I believe when you set a pollInterval in your options, apollo immediately starts polling for you.

@numso Unfortunately this was not the case, that's why I assumed I need to call `startPolling` manually. In any way, I still can't get my `useQuery` using a `pollInterval` to work. Any ideas?

**Comment by mrtnpro** [comment]
My mistake. Everything is working just fine. Somehow I was expecting `pollInterval` to be passed as `variable: {...}` inside the request payload. Closing issue 🤦‍♂️
