### ISSUE TITLE
Mutation refetchQueries logic is missing

### ISSUE THREAD

**Issue by Lepozepo** [trojanowski/react-apollo-hooks#147]
The logic found [here](https://github.com/apollographql/react-apollo/blob/master/src/Mutation.tsx#L213) is missing from `useMutation` which is causing `refetchQueries` in the shape of `refetchQueries: ['nameOfQuery']` to fail.

**Comment by lukasluecke** [comment]
If you look at the comment above these lines you'll see that passing queries like that is discouraged and will be removed in a future version of Apollo.

I'm not sure if it should be added to this library - do we care about full compatibility with current Apollo, or not? @trojanowski

**Comment by Lepozepo** [comment]
Yeah, I can see why. Maybe adding a note in the docs that that particular feature is disabled would be useful as people using `Mutation` and `Query` may still be using it.

**Comment by trojanowski** [comment]
> I'm not sure if it should be added to this library - do we care about full compatibility with current Apollo, or not? @trojanowski

No, we don't - especially not for deprecated features or edge cases.

> Yeah, I can see why. Maybe adding a note in the docs that that particular feature is disabled would be useful as people using Mutation and Query may still be using it and not be aware of the deprecation.

I'd accept a PR with that.

**Comment by Negan1911** [comment]
I don't think that this is an edge case, also, I can't find where is said that is going to be deprecated, actually passing `refetchQueries` as an array of string is the only way to refetch the previous query with the same parameters previous variables, using `refetchQueries: { query: MY_QUERY }` sends and `{}` as variables so I can't refetch it properly.

**Comment by Lepozepo** [comment]
@Negan1911 the "proper" way to refetch is to set those previous variables within the refetch in some way (most ways suck IMHO). I wrote a temporary `useMutation` that works like `const [mutator, mutatorMutationResult] = useMutation(props)`. It seems pretty stable right now but I haven't released it as an NPM package yet considering react apollo is releasing their own official version soon (currently in beta 7 apparently).

```
import { useState, useEffect, useContext } from 'react';
import { ApolloContext } from 'react-apollo';

export default function useMutation(mutation, props) {
  const { client, operations } = useContext(ApolloContext);
  const [mutationResult, setMutationResult] = useState({
    loading: false,
    error: undefined,
    data: undefined,
  });
  const [mutatorProps, setMutatorProps] = useState(props);
  const [runner, setRunner] = useState({ counter: 0 });

  useEffect(() => {
    let didCancel = false;

    async function mutate() {
      try {
        if (!didCancel) setMutationResult({ ...mutationResult, error: undefined, loading: true });

        const { refetchQueries } = mutatorProps;
        let parsedRefetchQueries = refetchQueries;
        if (refetchQueries && refetchQueries.length && Array.isArray(refetchQueries)) {
          parsedRefetchQueries = refetchQueries.map((x) => {
            if (typeof x === 'string' && operations) return operations.get(x) || x;
            return x;
          });
        }

        const res = await client.mutate({
          mutation,
          ...mutatorProps,
          refetchQueries: parsedRefetchQueries,
        });
        if (!didCancel) {
          setMutationResult({
            ...mutationResult,
            loading: false,
            error: undefined,
            data: res,
          });
          runner.resolve(res);
        }
      } catch (err) {
        if (!didCancel) {
          setMutationResult({
            ...mutationResult,
            loading: false,
            error: err,
            data: undefined,
          });
          runner.reject(err);
        }
      }
    }

    if (runner.counter !== 0) mutate();

    return () => {
      didCancel = true;
      if (runner.reject) runner.reject({ canceled: true });
    };
  }, [runner.counter, mutatorProps, mutation]);

  function runMutation(runMutationProps) {
    return new Promise((resolve, reject) => {
      setMutatorProps({ ...props, ...runMutationProps });
      setRunner({ counter: runner.counter + 1, resolve, reject });
    });
  }

  return [runMutation, mutationResult];
}
```

**Comment by Negan1911** [comment]
Thanks for the example, either way I wouldn’t want to actually break my head as you did for trying to refetch a simple list, I would love to check with @trojanowski that this isn't an edge case, is the only way to refetch queries in a simple manner, and if he agrees, i can even actually try to help with a PR.

**Comment by Negan1911** [comment]
@Lepozepo Again, thanks for your quick response, found an easy way by spying on the Apollo internals which doesn't involve doing some cancellation logic:

```js
import { getOperationName } from 'apollo-link'
import {
  useApolloClient,
  useQuery as useQueryBase,
  useMutation as useMutationBase
} from 'react-apollo-hooks'

const GetQueries = (store, queries) => {
  return queries
    ?.map(query => {
      if (typeof query === 'string') {
        const queries = Object.keys(store).map(_ => store[_])
        const query = queries.find(q => getOperationName(q.document))
        // Can be undefined if the query wasn't executed, but we catch that later
        return query
      }
      // If query is not a string, we just return it
      return query
    })
    .filter(_ => _ != null)
}

export const useMutation = (mutation, { refetchQueries, ...options } = {}) => {
  const client = useApolloClient()
  const _ = useMutationBase(mutation, {
     refetchQueries: ParseRefetchQueries(client.queryManager.queryStore.store, refetchQueries)
  })

  return _
}
```

It could be improved but it would make this more difficult to show.

**Comment by Negan1911** [comment]
So, i've got into a solution that doesn't involve writing a lot of code, and potentially will also solve #107:

I just wrapped both `useQuery` and `useMutation` like this:

```js
import { getOperationName } from 'apollo-link'
import {
  useQuery as useQueryBase,
  useMutation as useMutationBase
} from 'react-apollo-hooks'

export const useQuery = (query, options) => {
  const _ = useQueryBase(query, options)
  operations.set(getOperationName(query), {
    query,
    variables: options.variables
  })

  return _
}

export const useMutation = (mutation, options) => {
  const _ = useMutationBase(mutation, {
    ...options,
    refetchQueries:
      options &&
      options.refetchQueries &&
      options.refetchQueries.map(x => {
        if (typeof x === 'string' && operations.get(x)) {
          return operations.get(x)
        }

        return x
      })
  })

  return _
}
```

This is nothing more than a reimplementation of the missing code, @trojanowski I understand that you don't want to put something flagged as "deprecated". But on actual terms there's no other way around, even if is discouraged, not a single way was presented to properly replace the query as string on refetchQueries. Not supporting this will render many things unusable, not talking about edge cases, something plain simple as rendering a list on `/list`, creating a new item at `/list/new` and going back will fail if you use strings on `refetchQueries`, which, if you're using pagination or something else, you can't just ask for the previous variables.

**Comment by hmeerlo** [comment]
Ok, obviously this project is on a dead-end. Multiple issues for this problem but no willingness to fix it. And it is a rather basic problem, nobody wants to display outdated values.

**Comment by Lepozepo** [comment]
@hmeerlo the ones from the apollo team are looking pretty good [here](https://www.npmjs.com/package/@apollo/react-hooks) also

**Comment by hmeerlo** [comment]
Yes thanks, I just switched to that but it still gives me some issues. Which is expected because it is still in beta.

**Comment by ravikiranr26** [comment]
Hi Guys, any update on refetchQueries with react-apollo-hooks or @apollo/react-hooks. 
Still couldn't get it working when i want to use the id generated in db on create and show it on a list. :)

**Comment by Lepozepo** [comment]
@ravikiranr26 feel free to use [apollo-hooks-refetch](https://www.npmjs.com/package/apollo-hooks-refetch) it's very basic (no SSR support). I'll be patching it pretty often before `@apollo/react-hooks` makes its way in.

**Comment by ravikiranr26** [comment]
@Lepozepo Thanks for the reply and info. Would give a try and keep you posted on this.

**Comment by hugoh59** [comment]
I can't figure out why my code isn't working:

`const [createUser] = useMutation(CREATE_USER);
  const createUserHook = ({image, image_name, first_name}) => {
    return createUser({
      variables: { image: image.data, image_name: image_name, first_name: first_name },
      refetchQueries: [{ query: FETCH_USER }]
    })
  }`
