### ISSUE TITLE
Add ability to specify state dependencies to useQuery

### ISSUE THREAD

**Issue by LarsKoelpin** [trojanowski/react-apollo-hooks#148]
Hi, first of all thanks for this library.

## Motivation
I'm currently developing an application where a global Role selector exists and the user can switch its role. Based on this role i need different data for my components.

## The Problem
For demonstration purposes lets imagine I have a state which holds the current Role of my user (admin, owner).
If my User role is in state "admin" I need to fetch all Person Profiles while if my User role is in state "owner" I need to fetch my own Profile. 

I therefore could simply fetch all data for the roles
```jsx
// ... const [currentRole, setCurrentRole] = useState("admin")
const adminData = useQuery(forAdmin)
const ownerData = useQuery(forOwner)
```
which would mean I'm going to fetch admin and user data, altough i need just one if them and one of them is always expected to fail due to role restrictions.
Wrapping the queries in if-statements is not allowed due to hook rules.
> Don’t call Hooks inside loops, conditions, or nested functions.

## Proposed solution
In my opinion it would be a great extension to add the ability to optionally specify dependencies like useEffect from react does, which when changed, reevaluates the query as this probably would solve my problem of dynamic queries.
I created an hypothetical solution of this here:
https://codesandbox.io/s/pyynmzqz8j

What do you think of this proposal?

Greetings

**Comment by trojanowski** [comment]
@LarsKoelpin yes, I think `skip` should work for you.

**Comment by LarsKoelpin** [comment]
I didn't know about this option. Guess this solves my problem, thanks!

Therefore closing the ticket.
