### ISSUE TITLE
fetch-and-network is missing from useQuery

### ISSUE THREAD

**Issue by duongdev** [trojanowski/react-apollo-hooks#163]
Seems in the new version of apollo-client, the `FetchPolicy` interface is no longer contains `cache-and-network` option so react-apollo-hooks throws error when I use `fetchPolicy: cache-and-network` with `useQuery`.

https://github.com/apollographql/apollo-client/blob/bd7dc77e1cf897a74d86d2e8728daf37af8b5e3c/packages/apollo-client/src/core/watchQueryOptions.ts#L18

**Comment by markpradhan** [comment]
You can do this in the meanwhile.

```
  useQuery(QueryUserProfile, {
    suspend: false,
    fetchPolicy: 'cache-and-network',
  } as any)
```
