### ISSUE TITLE
Future of this project?

### ISSUE THREAD

**Issue by FredyC** [trojanowski/react-apollo-hooks#187]
@trojanowski Perhaps it could be a good idea to state what are your intentions here. With official Apollo support coming out soon, I assume it's safe to call this project deprecated? Unless there are some maintainers willing to take over.

It's totally great you have done this when Hooks came out. It helped to bridge that gap in technology. Appreciate your work here 💯 

Honestly, I've looked through the code of apollo hooks and it's so much cleaner and lean. No offense :) The code in here was obviously made to quickly satisfy the need of masses, nothing wrong about that.

**Comment by trojanowski** [comment]
@FredyC as I said before I'm going to deprecate this library as soon as the official support for hooks will be available. Just published version 0.5.0 should even ease the migration. :) Until then it's possible I'll publish some bugfix releases - I'm still using this lib personally. I'm also going to add info to the README about the beta version of the official hooks.

**Comment by trojanowski** [comment]
> I'm also going to add info to the README about the beta version of the official hooks.

Done in <https://github.com/trojanowski/react-apollo-hooks/commit/a0750ec5a2b48925edae1f5e6ec24745f524b13d>.

> Just published version 0.5.0 should even ease the migration.

I wasn't aware of <https://github.com/apollographql/react-apollo/issues/3189>. I hope they bring back the previous version of the API.

**Comment by FredyC** [comment]
@trojanowski Yea, I was also surprised by it ... https://github.com/apollographql/react-apollo/pull/3199#issuecomment-508746470

**Comment by mrtnpro** [comment]
@trojanowski Just upgraded for the sweet mutation tuples. In the changelog you mention
> now Apollo Client >= 2.6.0 is required to use this library

However, according to `react-apollo`'s changelog there is no such version. Latest one seems to be `2.5.7`. Am I missing something?

**Comment by FredyC** [comment]
`apollo-client` !== `react-apollo` ;)

![image](https://user-images.githubusercontent.com/1096340/60923861-21f9d900-a2a0-11e9-8b49-a0b56d308c68.png)

**Comment by mrtnpro** [comment]
🤦‍♂ @FredyC You are totally right, my mistake. Thanks for pitching in, tuples are working now ❤️

**Comment by hwillson** [comment]
@trojanowski @FredyC We're considering switching `useMutation` back. Thanks for bearing with us on this, and voicing your concerns. Switching things around sounded great in theory, but I'm starting to be really glad I didn't publish a new beta with those changes. We'll get this figured out tomorrow.

**Comment by evanheckert** [comment]
Just wanted to say thank you, @trojanowski , for the effort put into this. It has served us very well for multiple projects, and is a real pleasure to use! Bittersweet to start transitioning to the 'official' hooks package now.

**Comment by maxschmeling** [comment]
I also just wanted to say that I really appreciated that this library existed until the official support came out. Thanks for your work on this.
