### ISSUE TITLE
Conditionally firing a query

### ISSUE THREAD

**Issue by shlomokraus** [trojanowski/react-apollo-hooks#21]
I am trying to implement a conditional pattern which I am not sure how it should work with hooks. 
I have one query asking for currentUser and only when and if it returns a userId I will execute the query. 

By the rules of hooks, you must not nest hooks inside conditions or loops, so how can I achieve this? 

This is a sample of my custom hook: 

```ts
function useSomething() { 
  const [userId] = useCurrentUser();
  // Here we need to skip the query
  const { data, errors } = useQuery(query, { variables: {userId} });
  // Do some stuff and return data
 return [data, errors]
}
```

**Comment by trojanowski** [comment]
Hi @shlomokraus

Right now the only way to do it is to conditionally render a component using the `useQuery` hook. I think we could add `skip` option to it.  The query wouldn't run if it were equal to true.
Also please look at https://github.com/trojanowski/react-apollo-hooks/issues/18#issuecomment-438191372

**Comment by shlomokraus** [comment]
I also think that adding "skip" or similar is the best solution. Rendering the component conditionally will break encapsulation.
