### ISSUE TITLE
Adding more ObservableQuery function to useQuery

### ISSUE THREAD

**Issue by atoy40** [trojanowski/react-apollo-hooks#24]
Hello,

currently, only fetchMore() is added to the useQuery result. Is it possible to add more functions, like refetch(), start/stop polling... and more (https://github.com/apollographql/react-apollo/blob/e95e5fc60a7a52d7c54e1d55fa142e0137e4042f/src/Query.tsx#L49)

Thanks
Anthony.

**Comment by trojanowski** [comment]
Hi,

I published version 0.1.7 which adds those functions, with the exception of `subcribeToMore` - I think it would be problematic to use with hooks and I'm going to implement a separate hook for mutations in https://github.com/trojanowski/react-apollo-hooks/issues/22
