### ISSUE TITLE
Network error is not reported in errors and loading stays true

### ISSUE THREAD

**Issue by shlomokraus** [trojanowski/react-apollo-hooks#29]
When useing `useQuery` (with suspense false), I get a network error, but the hook state stays with "loading: true" and errors undefined. networkState is still 1.

**Comment by umidbekkarimov** [comment]
You can use `errorPolicy=all` as a workaround.
I guess the problem is that subscription error handler not passed here  https://github.com/trojanowski/react-apollo-hooks/blob/master/src/index.js#L31

**Comment by mateusznowosielski** [comment]
I have exactly the same issue as @shlomokraus described. Changing `errorPolicy='all'` doesn't make any difference - I tried to set that for individual query and globally in ApolloClient level. With `<Suspense>` it works as expected. I'm using version 0.2.1.

**Comment by mateusznowosielski** [comment]
Thanks @umidbekkarimov this is very helpful. Error gets properly handled, I also checked the `skip` option and I like the new typescript aspect. Hope it gets merged.

**Comment by trojanowski** [comment]
I think it will be merged soon - I'm going to review it tomorrow.

**Comment by cescox** [comment]
Hello, any news on this issue?
