### ISSUE TITLE
Update query result after mutation

### ISSUE THREAD

**Issue by Nikosmonaut** [trojanowski/react-apollo-hooks#31]
Hello,

I'm trying to see my mutation after writing a query into the store.
Previously on a mutation update when I write something to the store with writeQuery all queries results were updated automatically on screen.

It seems that now useQuery is not called twice on rerender when no input args changed. I found a workaround something like this :
``    const { data, refetch, fetchMore } = useQuery(POST_FEED, {
        variables: variables,
        key: something
    });
``

And on each mutation I change the key value. But I don't think it's the solution for the problem.

**Comment by trojanowski** [comment]
@Nikosmonaut I'm closing this issue. Please add a comment if you still have this problem and are able to create a reproduction.
