### ISSUE TITLE
Using it with the Appsync client

### ISSUE THREAD

**Issue by cuttlas** [trojanowski/react-apollo-hooks#32]
Hi, I guess it's just not possible right now, but just to confirm I didn't do anything wrong:

```jsx
import { ApolloProvider } from "react-apollo-hooks";
import { Rehydrated } from "aws-appsync-react";
import appsyncClient from "./appsyncClient";

<ApolloProvider client={appsyncClient}>
    <Rehydrated>
      <App />
    </Rehydrated>
</ApolloProvider>
```
throws the following error:

> Unhandled Rejection (TypeError): Cannot read property 'hydrated' of undefined

If I use the ApolloProvider from react-apollo, it works fine. I don't know how difficult it would be to add support for it.

Thanks.

**Comment by bebbi** [comment]
@cuttlas a couple months later, can you still confirm that `react-apollo-hooks` and `appsync` are nicely working together?

**Comment by trblackw** [comment]
I'd like to second @cuttlas 's question

**Comment by yuritoledo** [comment]
@cuttlas ?

**Comment by manicode097** [comment]
This seems to be broken again with latest versions. Anyone else facing similar issue?
I am getting error - "Warning: Failed context type: The context `client` is marked as required in `Rehydrated`, but its value is `undefined`.
"

**Comment by KosGrillis** [comment]
> This seems to be broken again with latest versions. Anyone else facing similar issue?
> I am getting error - "Warning: Failed context type: The context `client` is marked as required in `Rehydrated`, but its value is `undefined`.
> "

I'm facing the same issue after upgrading to react-apollo 3.0.1

**Comment by jcwrightson** [comment]
Broken!!

**Comment by jcwrightson** [comment]
Can we reopen this issue? @cuttlas wrapping the providers does not seem to fix the issue!

**Comment by j0b0sapi3n** [comment]
Have this same issue after upgrading to react-apollo 3.0.1

**Comment by alex-suarez-lmnd** [comment]
Same issue here with react-apollo 3.1.0 and a fresh setup of CRA.

**Comment by ph0ph0** [comment]
SAME ISSUE STILL

**Comment by alex-suarez-lmnd** [comment]
Updated to react-apollo 3.1.1 and the issue persists

**Comment by alex-suarez-lmnd** [comment]
Moving back to @2.5.8 works. This is so far the only workaround I could find. Hope it helps

**Comment by emontenegr** [comment]
I'm getting this too please help!

**Comment by Obrazcoff** [comment]
Same issue on my project!

**Comment by kierancrown** [comment]
I managed to fix this by creating a custom Rehydrated component and passing the client to both the provider and the rehydrated component. The Rehydrated.js file is as follows:
```
import React, { Component } from 'react';
import PropTypes from 'prop-types';

import AWSAppSyncClient from 'aws-appsync';

const Rehydrate = (props) => (
  <div
    className={`awsappsync ${
      props.rehydrated ? 'awsappsync--rehydrated' : 'awsappsync--rehydrating'
    }`}
  >
    {props.rehydrated ? props.children : <span>Loading...</span>}
  </div>
);

class Rehydrated extends Component {
  static propTypes = {
    render: PropTypes.func,
    children: PropTypes.node,
    loading: PropTypes.node,
    client: PropTypes.instanceOf(AWSAppSyncClient).isRequired,
  };

  constructor(props) {
    super(props);

    this.state = {
      rehydrated: false,
    };
  }

  async componentWillMount() {
    await this.props.client.hydrated();

    this.setState({
      rehydrated: true,
    });
  }

  render() {
    const { render, children, loading } = this.props;
    const { rehydrated } = this.state;

    if (render) return render({ rehydrated });

    if (children) {
      if (loading) return rehydrated ? children : loading;

      return <Rehydrate rehydrated={rehydrated}>{children}</Rehydrate>;
    }
  }
}

export default Rehydrated;

```
