### ISSUE TITLE
Roadmap to complete stable version

### ISSUE THREAD

**Issue by umidbekkarimov** [trojanowski/react-apollo-hooks#43]
I’m trying to figure out a list to make react-apollo-hooks analogue to current react-apollo version.

List from @trojanowski (https://github.com/trojanowski/react-apollo-hooks/issues/40#issuecomment-449486782):

- useSubscription (#22 and #37)
- skip option for useQuery (#21)
- server-side rendering (#8) - also with react-apollo compatibility
- TypeScript rewrite (#39)
- (probably) changes to error management (#28)

My observations (open for suggestions)
- Refactor client+query caching: use react context, add error messages (inherit from react-apollo).
- Add more tests with react-profiler (started in #42).
- Add tests from react-apollo (maybe fix some edge cases).
- Bundle with rollup, report bundle size.
- Add tests for useQuery imperative methods.
- Find a good way to replace lodash with interal utilities.
- Add more recipes and examples (most developers mindset is not prepared for hooks and Suspense yet).

PRs:
- [x] TypeScript Rewrite (#39)
- [x] useSubscription (#37)
- [x] SSR (#44)
- [x] Skip option for useQuery (#21)
- [ ] Support all fetch policies in suspense mode (#15)

**Comment by trojanowski** [comment]
> Refactor client+query caching: use react context, add error messages (inherit from react-apollo).

Do you mean replace the WeakMap used in _queryCache.js_ with React context? If so I'm not sure it's a good idea. It was introduced in https://github.com/trojanowski/react-apollo-hooks/commit/246208c69a19dc00c8ad1bf15b18a65cf6f6d7ee to fix #23. React context wouldn't work in the following case:

```javascript
render(
  <Suspense fallback={<MyFallbackComponent />}>
    <ApolloProvider client={client}>
      <MyComponent />
    </ApolloProvider>
  </Suspense>
);
```

If `<MyComponent />` were suspended then `<ApolloProvider />` would lose its state, and I guess it's a place where you'd like to store the query cache which should be passed by context. Of course, we could require to always use the provider component at the top of the react tree or require users to create the cache outside the tree and pass it as a property, but I think the current solution is the most ergonomic one.

> Bundle with rollup, report bundle size.

Do you mean use rollup for creating a UMD version, ready to use with `<script>` HTML tags? Are there any benefits of using rollup for creating CJS or ES modules versions?

> Find a good way to replace lodash with interal utilities.

Right now only a small subset of lodash is added to the final app bundle, and it may be already added by other libraries. So I'm not sure if moving it to internal utilities would lower its size.

> Add more recipes and examples (most developers mindset is not prepared for hooks and Suspense yet).

👍  Great idea. I'd appreciate any contributions here.

**Comment by umidbekkarimov** [comment]
> Do you mean replace the WeakMap used in queryCache.js with React context? If so I'm not sure it's a good idea. It was introduced in 246208c to fix #23.

I was thinking about simple context `createContext(new WeakMap())` that will use same singleton instance but still allow to inject another WeakMap instance in unit tests.

> Do you mean use rollup for creating a UMD version, ready to use with <script> HTML tags? Are there any benefits of using rollup for creating CJS or ES modules versions?

Mostly for [rollup-plugin-size-snapshot](https://github.com/TrySound/rollup-plugin-size-snapshot) that allows to track bundle size between PRs. Web community loves to freak out about npm package sizes.

> Right now only a small subset of lodash is added to the final app bundle, and it may be already added by other libraries. So I'm not sure if moving it to internal utilities would lower its size.

Lately github introduces new feature that bugs you about unstable libs. So even if my code is 100% stable - I have to publish new version with updated dependency version. That's the reason I'm removing third party utilities from my repos.
But it's just a suggestion.

**Comment by lindskogen** [comment]
What about supporting all the fetch options? 

`"cache-first" | "cache-and-network" | "network-only" | "cache-only" | "no-cache" | "standby"`

I would like to see `"cache-and-network"` for my use-cases

**Comment by trojanowski** [comment]
@lindskogen There are supported right now in the non-suspense mode. With suspense, we'll have to emulate these options. I tried to add support for `cache-and-network` in #15. I don't need them right now and not sure I'll have time to work on them in the near future, but I'd accept PR.

**Comment by rostero1** [comment]
I think the problem was that sometimes it was using the variables from fetchMore and sometimes it was using variables from useQuery.  After I have them both use the same variables, the problem seemed to resolve itself.  How do I know which variables are being applied, though?

**Comment by trojanowski** [comment]
@rostero1 Could you please open a separate issue with your question? Let's focus about the roadmap here.

**Comment by schlesingermatthias** [comment]
Hi @trojanowski, in #15 you said you're gonna wait with its implementation until suspense for data fetching is release. According to the react roadmap that's not gonna happen before mid 2019. Any plans to release the other four PRs (especially #21 ) before that? That would be very helpful. Thank you

**Comment by trojanowski** [comment]
@schlesingermatthias all of those PRs are already released and available in the latest version.

**Comment by trojanowski** [comment]
I'm going to close this issue because IMO this library can be considered stable to use (in the non-suspense mode). I created a new meta issue with a list of breaking changes planned for the next version: #138.
