### ISSUE TITLE
SuspenseProps is imported in SuspenseSSR but react doesn't have it.

### ISSUE THREAD

**Issue by mateusznowosielski** [trojanowski/react-apollo-hooks#63]
I updated to latest version 0.3.0 and saw below error being thrown. I thought that maybe it's something new added to React 16.8.0-alpha but no. What is this SuspenseProps imported from 'react'?

.../node_modules/react-apollo-hooks/lib/SuspenseSSR.d.ts
Type error: Module '".../node_modules/@types/react/index"' has no exported member 'SuspenseProps'.  TS2305

  > 1 | import { SuspenseProps } from 'react';
      |          ^
    2 | export declare function unstable_SuspenseSSR({ children, fallback }: SuspenseProps): JSX.Element;

**Comment by trojanowski** [comment]
@mateusznowosielski Could you please ensure you're using a newest version of `@types/react` package?

**Comment by mateusznowosielski** [comment]
@trojanowski That was it thanks a ton.
