### ISSUE TITLE
Run useQuery() multiple times if a variable is updated aka refresh Query

### ISSUE THREAD

**Issue by dan003400** [trojanowski/react-apollo-hooks#66]
How can we run useQuery manually again if lets say a state attribute is updated.

**Comment by dan003400** [comment]
So I have noticed I am able to get access to a refetch() function when initializing the useQuery, but I have not been successful using useEffect to watch for changes and call refetch() with the new variables.

Has anyone had any success with the refetch() function?

Thanks,

Dan

**Comment by adamtysonsmith** [comment]
@dan003400 what was your solution to this?
