### ISSUE TITLE
how to check if fetching more, network status undefined

### ISSUE THREAD

**Issue by zebapy** [trojanowski/react-apollo-hooks#67]
Using the query as 

```js
  const { data, loading, networkStatus, fetchMore } = useQuery(query, {
    variables,
    skip,
    notifyOnNetworkStatusChange: true
  });

```

`networkStatus` seems undefined when console logging so I can't do `const loadingMore = networkStatus === 3`

**Comment by trojanowski** [comment]
It's already fixed in v0.4.0 for the non-suspense mode. For suspense the fix is quite hacky so I decided to postpone it until Suspense for data fetching is considered ready by the React team. Added to a list of know issues in #88.
