### ISSUE TITLE
Feat: Key prop in useMutation to update item in the cache

### ISSUE THREAD

**Issue by JClackett** [trojanowski/react-apollo-hooks#70]
With react-apollo, it's possible to set a key={id} prop on the Mutation component 

e.g 
```jsx
	<Mutation mutation={UPDATE_TODO} key={id}>
```

Apollo then updates the correct item in the cache, wondering if this is currently possible with this library?

**Comment by rostero1** [comment]
I was very confused as to why my cache wasn't updating and wound up defining my own dataIdFromObject that uses object.id, but being able to supply a key seems much better.

**Comment by trojanowski** [comment]
@JClackett You can always use the `update` option to change any item in the cache. Doesn't it solve your use case?

**Comment by JClackett** [comment]
@trojanowski yeah that's what i've been doing, I was just checking to see if there was an option like the react-apollo library, as it's a bit cleaner :)
