### ISSUE TITLE
Prop data from query result should not be optional

### ISSUE THREAD

**Issue by danielbischoff** [trojanowski/react-apollo-hooks#79]
I think the property data from useQuery result should not be optional.
When we look in the [docs](https://www.apollographql.com/docs/react/essentials/queries.html#render-prop): 

> An object containing the result of your GraphQL query. Defaults to an empty object.

It defaults to an empty {} object. Event when I console.log, I never see data being undefined.

Apollo itself defines it as
```
ApolloCurrentResult<T> = {
    data: T | {};
}
```
and

```
ApolloQueryResult<T> = {
    data: T;
}

```
As we can see, it is either T or {} but never optional (undefined)
Thus the interface QueryHookState<TData> should not define data as optional.

**Comment by trojanowski** [comment]
It actually can be optional if the query is skipped: <https://github.com/trojanowski/react-apollo-hooks/blob/master/src/useQuery.ts#L173-L181>. It's similar to the way how react-apollo implements it: https://github.com/apollographql/react-apollo/blob/5cb63b3625ce5e4a3d3e4ba132eaec2a38ef5d90/src/Query.tsx#L376-L381

**Comment by danielbischoff** [comment]
> It actually can be optional if the query is skipped: https://github.com/trojanowski/react-apollo-hooks/blob/master/src/useQuery.ts#L173-L181. It's similar to the way how react-apollo implements it: https://github.com/apollographql/react-apollo/blob/5cb63b3625ce5e4a3d3e4ba132eaec2a38ef5d90/src/Query.tsx#L376-L381

I see, thank you for your reply!
