### ISSUE TITLE
Consider allowing `client` to be passed as an argument.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [trojanowski/react-apollo-hooks#85]
The [error message](https://github.com/trojanowski/react-apollo-hooks/blob/75fbecd5004e606e8f6c8868f8dd1e23a3cca57b/src/ApolloContext.tsx#L27-L30) from `useApolloClient` suggests that it should be possible to pass the `ApolloClient` as a prop.  While it's just the error message from `react-apollo` verbatim, it still seems like a valid enough option.

**Comment by alexkirsz** [comment]
I think it would make sense for `useQuery` to accept a `client` option, to opt-out of the default "read client from context" behavior. This way we can implement custom `useQuery` hooks that potentially communicate with different clients.

**Comment by trojanowski** [comment]
Is it something you need or should I just change the message?

**Comment by wtgtybhertgeghgtwtg** [comment]
I do have a use for it (running a query in a top-level `App` component in `next` where the provider has yet to be made available) that I believe is valid.  It may also make testing a little cleaner.

**Comment by alexkirsz** [comment]
I have a case where I need to query multiple clients. Although not documented, the `Query` and `Mutation` components [do accept a `client` prop](https://github.com/apollographql/react-apollo/blob/6a02550db2b14881582ede2c4e1a3e1ef51f0b7a/src/Mutation.tsx#L60), so I think it'd makes sense for their hooks counterpart to do as well. With the new Context API and `useContext`, I think the `ApolloContext` API is simple enough to reimplement for this kind of advanced use case.
