### ISSUE TITLE
How to handle loading and error state in a generic way?

### ISSUE THREAD

**Issue by nareshbhatia** [trojanowski/react-apollo-hooks#89]
In react-apollo 2.x, I used to handle loading and error state in a generic way by encapsulating the `<Query>` component as follows:

```
import * as React from 'react';

import { Query } from 'react-apollo';
import { CenteredMessage } from './centered-message';

export const DefaultQuery = ({ query, variables = {}, children }) => (
    <Query query={query} variables={variables}>
        {({ loading, error, data, fetchMore, subscribeToMore }) => {
            if (loading) {
                return <CenteredMessage>Loading...</CenteredMessage>;
            }

            if (error) {
                return <CenteredMessage>{error.message}</CenteredMessage>;
            }

            return children({ data, fetchMore, subscribeToMore });
        }}
    </Query>
);
```

What would be the equivalent pattern with react-apollo-hooks? I started writing a component similar to the above, but it doesn't feel right to reintroduce render props in a hooks world:

```
import React, { ReactNode } from 'react';

import { OperationVariables } from 'apollo-client';
import { DocumentNode } from 'graphql';
import { useQuery } from 'react-apollo-hooks';
import { CenteredMessage } from './centered-message';

export interface DefaultQueryProps {
    query: DocumentNode,
    variables: OperationVariables,
    children: ReactNode
}

export const DefaultQuery = ({ query, variables = {}, children }: DefaultQueryProps) => {
    const { data, error, loading } = useQuery(query);
    if (loading) {
        return <CenteredMessage>Loading...</CenteredMessage>;
    }

    if (error) {
        return <CenteredMessage>{error.message}</CenteredMessage>;
    }

    // TODO: include fetchMore and subscribeToMore when available
    // return children({ data, fetchMore, subscribeToMore });
    return children({ data });
};
```

Besides, the above pattern works well for a single query. How would you enhance it to handle multiple parallel queries? In the render props world, I used to nest `<DefaultQuery>` components to achieve that, but its not very elegant. See my example [here](https://github.com/nareshbhatia/graphql-bookstore/blob/master/apollo-bookstore-client/src/components/books/books-container.tsx) - it uses a triple-nested `<DefaultQuery>`.

**Comment by FredyC** [comment]
Haha, definitely kinda twisted logic to convert hook back to render prop pattern :)

For loading state, there is a hope that Suspense will solve that more gracefully so you don't need to make conditions for it. Error handling is always tricky and there are numerous ways how to deal with it and kinda depends on the app.

I've seen this pattern somewhere which isn't too bad.

```tsx
const MyComponent = () => {
    const { data, loading, error } = useQuery(query);
    return (<HandleQuery loading={loading} error={error}>
      // what is shown in success scenario
    </HandleQuery>)
};
```

**Comment by FredyC** [comment]
Btw, regarding error handling, have a look at #28

**Comment by nareshbhatia** [comment]
Thanks, @FredyC. `<HandleQuery>` seems like a nice pattern. Will give it a try.

**Comment by nareshbhatia** [comment]
Tried to implement this, but stuck on a TypeScript error. Please see my [StackOverflow question](https://stackoverflow.com/questions/54905376/type-error-jsx-element-type-null-undefined-is-not-a-constructor-functi).

**Comment by FredyC** [comment]
@nareshbhatia I've posted an answer for you there.

**Comment by nareshbhatia** [comment]
@FredyC, thanks for your help on StackOverflow. I have now fully converted my [GraphQL tutorial](https://github.com/nareshbhatia/graphql-bookstore) from render props to hooks (including `useSubscription` introduced in 0.4.1). I am sure there is room for improvement, so your feedback and suggestions would be very welcome.

I tweeted about my conversion experience [here](https://twitter.com/NareshJBhatia/status/1101554918132015105).

**Comment by nareshbhatia** [comment]
[@FredyC, I am replying on this thread just in case you did not see my Twitter reply]

As per your suggestion, I read up on Suspense. I get that I need to wrap my component in <Suspense fallback={<Loading />}>, but how can my component inform the parent that it is loading? The docs don't talk about that. It seems that React.lazy() has the magic built into it. I would appreciate any reference that talks about this.

**Comment by FredyC** [comment]
@nareshbhatia Sorry, not reading twitter much in past days :) Suspense for data fetching is not exactly finalized, but in your case, it would work just fine when you have multiple queries. With this lib, all you need to do is pass `suspend: true` option there and wrap the whole thing with Suspense to let the magic happen :)

**Comment by nareshbhatia** [comment]
Ah, I definitely glossed over the docs on that one! Implemented your suggestion [here](https://github.com/nareshbhatia/graphql-bookstore/blob/master/apollo-bookstore-client-with-hooks/src/components/books/books-container.tsx#L13-L34) and [here](https://github.com/nareshbhatia/graphql-bookstore/blob/master/apollo-bookstore-client-with-hooks/src/shell.tsx#L65-L70). Can you please let me know if I can do any better?

It would be even nicer if `useQuery()` would through exceptions - that would allow me to delete all the error handling from my component and let `ErrorBoundary` handle it.

**Comment by FredyC** [comment]
@nareshbhatia There is a work in progress PR #93 that improves error handling for mutations. When that gets through, queries will probably get some polish as well (#28).

Suspense is fine in such a simple case for sure, but there are definitely some promises from React team to provide some better tools for data fetching scenarios. Current Suspense is more meant for lazy loading.

**Comment by nareshbhatia** [comment]
Thanks @FredyC. The two references in your comment are indeed enlightening. Watching them!

**Comment by psaruks** [comment]
my solution for this case, it works with [Typescript Generics](https://www.typescriptlang.org/docs/handbook/2/generics.html)

QueryWrapper.ts

```
import { QueryResult } from "@apollo/client/react/types/types";

interface Props<TData, TVariables> {
  query: QueryResult<TData, TVariables>;
  children: (data: TData) => any;
}

export function QueryWrapper<TData, TVariables>({ query, children }: Props<TData, TVariables>) {
  if (query.loading) {
    return "loading...";
  }

  if (query.error) {
    return query.error.message;
  }

  if (!query.data) {
    return "Data is empty"
  }

  return children(query.data as TData);
}
```

usage:

```
const recipeQuery = useQuery<{ recipes: Recipe[] }>(GET_RECIPES);

<QueryWrapper query={recipeQuery}>
    {({recipes}) => (
       JSON.stringify(recipes)
    )}
</QueryWrapper>
```
