### ISSUE TITLE
useQuery variables as first class citizen

### ISSUE THREAD

**Issue by FredyC** [trojanowski/react-apollo-hooks#92]
Just opening a discussion while there is still a time for _drastic_ changes :)

From my experience like 95% of queries execution is about passing some variables to it. Sometimes you want to pass a `skip`, perhaps override `fetchPolicy`, but it's not that common.

That said I would like to propose following signature.

```ts
useQuery(query: DocumentNode, variables?: TVariables, options?: QueryOptions)
```

Ultimately it's no big deal as with hooks we can have own abstraction in the app code that does that. I just want to discuss if it's a good pattern worth considering to be standardized.

**Comment by trojanowski** [comment]
I considered it when I started implementing this library but finally decided against it. I actually thought that there would be a suggestion about API changes in the opposite site :) - to change it to something like:

```typescript
useQuery(options: QueryOptions)
```

and to require `query` to be a part of `options` - to make it more similar to apollo-client API.

One advantage of the current form is that all main hooks look kinda similar - all have two arguments - the first one is a GraphQL "query" and the second one are options. For `useQuery` other options than `variables` are probably really used not too often, but `update` for `useMutation` and `onSubscriptionData` for `useSubscription` are more common I think.

**Comment by FredyC** [comment]
Ok sure, just a wild idea. I already have the abstraction that does it and since nobody else seems too keen about it, let's leave it :)
