### ISSUE TITLE
Mutation refetchQueries does not set loading to true in useQuery

### ISSUE THREAD

**Issue by Drago96** [trojanowski/react-apollo-hooks#94]
Following the https://www.howtographql.com guide here, and I decided to spice things up by using hooks. I have the following query for fetching the feed:

```graphql
export const FEED_QUERY = gql`
  {
    feed {
      links {
        id
        url
        description
        createdAt
        postedBy {
          id
          name
        }
        votes {
          id
          user {
            id
          }
        }
      }
    }
  }
`;
```
and a simple useQuery which fetches the feed and then displays the data on the homepage:

```js
const { data, error, loading } = useQuery(FEED_QUERY);
```

then I have the following mutation on a different page which adds a new link to the feed:

```js

  const postMutation = useMutation(POST_MUTATION, {
    variables: { description, url },
    onCompleted: () => history.push("/"),
    refetchQueries: [
      {
        query: FEED_QUERY
      }
    ]
  });
```

After rerouting to the home page, the old feed is still displayed and after a couple of seconds after the refetch query is complete, the new updated feed is displayed. However for the duration while the refetch query is executing loading remains set to false for useQuery.

**Comment by lukasluecke** [comment]
This is the same behaviour as in Apollo itself, you need to work with the networkStatus in the returned object, and set notifyOnNetworkStatusChange to true in your hook call. https://www.apollographql.com/docs/react/essentials/queries.html#loading
