### ISSUE TITLE
endless looop upon react render when suspend: true

### ISSUE THREAD

**Issue by capaj** [trojanowski/react-apollo-hooks#96]
Since version 0.4.0 I am getting an infinite loop on startup of our app. 0.3.1 works fine, but 0.4.0 and 0.4.1 are ending in this loop:

![image](https://user-images.githubusercontent.com/1305378/53409770-22b16300-39c2-11e9-981d-3048dc92dcab.png)

my component uses the simple `useQuery` call.
Note this does not occur when I manually handle loading states-only when `suspend: true` is passed.

**Comment by lukasluecke** [comment]
Can you share your component code?

**Comment by capaj** [comment]
I can. It won't help I fear-it's a really simple component. Give me a 30 minutes.

**Comment by capaj** [comment]
this is how we got the provider set up:
![image](https://user-images.githubusercontent.com/1305378/53452154-d5b0a980-3a20-11e9-8b0c-b8463f4a4436.png)

it actually does it in any component, for example if I use the hook like this anywhere in my app:

```ts
const { data, loading } = useQuery(query, {
    variables: { filter: filterWithTopicId, topicId },
    suspend: true
  })
```

**Comment by lukasluecke** [comment]
That's weird indeed. I tried reproducing your issue, but was unable to.
Is there any way you could create a runnable example or share more of your code?

What does your query look like, how do you create your client, what versions of libraries (e.g. React) are you using, do you see any network request while running (and if so, what are the responses)?

**Comment by OlivierJM** [comment]
I am currently using the suspend:true in my code and I didn't notice unecessary re-renders.
It works pretty fine

**Comment by trojanowski** [comment]
@capaj Could you please provide a reproduction on https://codesandbox.io? As a source you can use https://www.graphqlhub.com (GraphQL API url: https://www.graphqlhub.com/graphql, [example query here](https://www.graphqlhub.com/playground?query=%7B%0A%20%20graphQLHub%0A%20%20giphy%20%7B%0A%09%09random(tag%3A%22javascript%22)%20%7B%0A%20%20%20%20%09id%0A%20%20%20%20%20%20url%0A%20%20%20%20%20%20images%20%7B%0A%20%20%20%20%20%20%20%20original%20%7B%0A%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%09%7D%0A%20%20%7D%0A%7D&variables=)).

**Comment by trojanowski** [comment]
@capaj I'm closing it right now. Please add a comment if you still have this problem and can provide a reproduction.

**Comment by wintercounter** [comment]
We're having the very same issue now. It started to happen after we dropped IE11 support for our codebase, removed babel-polyfill, fetch polyfill and transform-regenerator. We're still investigating what's happening.
