### ISSUE TITLE
useQuery should return cached data after error

### ISSUE THREAD

**Issue by madflanderz** [trojanowski/react-apollo-hooks#99]
When using fetchPolicy **cache-and-network** and then happens an error useQuery returns with empty data. I would expect that the previous data is returned. React-Apollo is doing this as well, you can see this here: https://github.com/apollographql/react-apollo/blob/master/src/Query.tsx#L444

Steps to reproduce:

- show component that uses useQuery with  fetchPolicy="cache-and-network", data is received
- disable network (or block graphql server request in dev tools)
- show component again, useQuery is executed again but fails with network error, data object is empty

Expected behaviour:
useQuery should return previous cached data when error happens.

I already tried the solution and it seems to work fine. What do you think about this?
https://github.com/madflanderz/react-apollo-hooks/commit/cad5f7525d93ad2d1f54df097623b4767fdfe89d

**Comment by pontusab** [comment]
Related? https://github.com/trojanowski/react-apollo-hooks/issues/74

**Comment by madflanderz** [comment]
No, the title looks similar but #74 is another problem. The usecase for this problem here is this:

- you have 2 pages in your app that each use useQuery with fetchPolicy="cache-and-network"
- visit both pages, user can see data from first requests
- turn of internet 
- visit both pages again, user should still use the app and see the data from the cache

**Comment by pontusab** [comment]
@madflanderz nice 👍

**Comment by trojanowski** [comment]
Should be fixed in v0.4.4.
